[workspace]
members = [
    "glacis-core",
    "glacis-launch",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Joe Braidwood <joe@glacis.io>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Glacis-io/glacis-cli"
